# SPDX-FileCopyrightText: 2026 Alexandr Savca
# SPDX-License-Identifier: GPL-3.0-or-later
option(
  'link_mode',
  type: 'combo',
  choices: ['shared', 'static'],
  value: 'shared',
  description: 'How libpkgsource-yaml links against external dependencies',
)
option(
  'tests',
  type: 'feature',
  value: 'enabled',
  description: 'Build and run the libpkgsource-yaml test suite',
)
option(
  'man_pages',
  type: 'feature',
  value: 'auto',
  description: 'Install generated manual pages',
)

option(
  'yaml_provider',
  type: 'combo',
  choices: ['libyaml'],
  value: 'libyaml',
  description: 'Qualified YAML event provider',
)

option(
  'html_docs',
  type: 'feature',
  value: 'disabled',
  description: 'Generate and install versioned static HTML documentation',
)
